
#include "nuitka/prelude.h"

// Sentinel PyObject to be used for all our call iterator endings. It will
// become a PyCObject pointing to NULL. It's address is unique, and that's
// enough for us to use it as sentinel value.
PyObject *_sentinel_value = NULL;

PyObject *const_int_0;
PyObject *const_str_dot;
PyObject *const_int_neg_1;
PyObject *const_int_pos_1;
PyObject *const_int_pos_2;
PyObject *const_int_pos_3;
PyObject *const_int_pos_4;
PyObject *const_int_pos_5;
PyObject *const_int_pos_8;
PyObject *const_str_chr_0;
PyObject *const_str_empty;
PyObject *const_str_space;
PyObject *const_dict_empty;
PyObject *const_int_pos_10;
PyObject *const_int_pos_16;
PyObject *const_int_pos_20;
PyObject *const_int_pos_32;
PyObject *const_int_pos_64;
PyObject *const_str_chr_44;
PyObject *const_bytes_empty;
PyObject *const_int_pos_255;
PyObject *const_str_newline;
PyObject *const_str_plain_X;
PyObject *const_str_plain__;
PyObject *const_str_plain_b;
PyObject *const_str_plain_c;
PyObject *const_str_plain_f;
PyObject *const_str_plain_h;
PyObject *const_str_plain_i;
PyObject *const_str_plain_o;
PyObject *const_str_plain_r;
PyObject *const_str_plain_s;
PyObject *const_str_plain_u;
PyObject *const_str_plain_w;
PyObject *const_str_plain_x;
PyObject *const_str_plain_y;
PyObject *const_tuple_empty;
PyObject *const_str_plain_io;
PyObject *const_str_plain_nt;
PyObject *const_str_plain_os;
PyObject *const_str_plain_rb;
PyObject *const_str_plain_PY3;
PyObject *const_str_plain_buf;
PyObject *const_str_plain_chr;
PyObject *const_str_plain_doc;
PyObject *const_str_plain_end;
PyObject *const_str_plain_get;
PyObject *const_str_plain_int;
PyObject *const_str_plain_key;
PyObject *const_str_plain_len;
PyObject *const_str_plain_map;
PyObject *const_str_plain_mod;
PyObject *const_str_plain_obj;
PyObject *const_str_plain_pop;
PyObject *const_str_plain_sep;
PyObject *const_str_plain_str;
PyObject *const_str_plain_sum;
PyObject *const_str_plain_sys;
PyObject *const_str_plain_val;
PyObject *const_str_plain_ver;
PyObject *const_str_plain_Font;
PyObject *const_str_plain_None;
PyObject *const_str_plain_Rect;
PyObject *const_str_plain_args;
PyObject *const_str_plain_argv;
PyObject *const_str_plain_blit;
PyObject *const_str_plain_bold;
PyObject *const_str_plain_copy;
PyObject *const_str_plain_data;
PyObject *const_str_plain_dict;
PyObject *const_str_plain_draw;
PyObject *const_str_plain_file;
PyObject *const_str_plain_font;
PyObject *const_str_plain_imap;
PyObject *const_str_plain_info;
PyObject *const_str_plain_init;
PyObject *const_str_plain_iter;
PyObject *const_str_plain_java;
PyObject *const_str_plain_join;
PyObject *const_str_plain_keys;
PyObject *const_str_plain_left;
PyObject *const_str_plain_line;
PyObject *const_str_plain_long;
PyObject *const_str_plain_mask;
PyObject *const_str_plain_name;
PyObject *const_str_plain_next;
PyObject *const_str_plain_open;
PyObject *const_str_plain_path;
PyObject *const_str_plain_quit;
PyObject *const_str_plain_read;
PyObject *const_str_plain_repr;
PyObject *const_str_plain_self;
PyObject *const_str_plain_send;
PyObject *const_str_plain_site;
PyObject *const_str_plain_size;
PyObject *const_str_plain_stop;
PyObject *const_str_plain_time;
PyObject *const_str_plain_type;
PyObject *const_str_plain_wait;
PyObject *const_str_plain_Color;
PyObject *const_str_plain_False;
PyObject *const_str_plain_Queue;
PyObject *const_str_plain_array;
PyObject *const_str_plain_ascii;
PyObject *const_str_plain_bytes;
PyObject *const_str_plain_close;
PyObject *const_str_plain_color;
PyObject *const_str_plain_empty;
PyObject *const_str_plain_event;
PyObject *const_str_plain_image;
PyObject *const_str_plain_input;
PyObject *const_str_plain_items;
PyObject *const_str_plain_level;
PyObject *const_str_plain_lower;
PyObject *const_str_plain_mixer;
PyObject *const_str_plain_mouse;
PyObject *const_str_plain_numpy;
PyObject *const_str_plain_print;
PyObject *const_str_plain_queue;
PyObject *const_str_plain_range;
PyObject *const_str_plain_right;
PyObject *const_str_plain_shell;
PyObject *const_str_plain_sound;
PyObject *const_str_plain_split;
PyObject *const_str_plain_start;
PyObject *const_str_plain_throw;
PyObject *const_str_plain_tuple;
PyObject *const_str_plain_types;
PyObject *const_str_plain_value;
PyObject *const_str_plain_width;
PyObject *const_str_plain_win32;
PyObject *const_str_angle_lambda;
PyObject *const_str_plain_Thread;
PyObject *const_str_plain_append;
PyObject *const_str_plain_bytes_;
PyObject *const_str_plain_darwin;
PyObject *const_str_plain_decode;
PyObject *const_str_plain_encode;
PyObject *const_str_plain_exists;
PyObject *const_str_plain_filter;
PyObject *const_str_plain_format;
PyObject *const_str_plain_getcwd;
PyObject *const_str_plain_height;
PyObject *const_str_plain_italic;
PyObject *const_str_plain_kwargs;
PyObject *const_str_plain_locals;
PyObject *const_str_plain_object;
PyObject *const_str_plain_pickle;
PyObject *const_str_plain_pygame;
PyObject *const_str_plain_remove;
PyObject *const_str_plain_render;
PyObject *const_str_plain_result;
PyObject *const_str_plain_rstrip;
PyObject *const_str_plain_sprite;
PyObject *const_str_plain_stdout;
PyObject *const_str_plain_strict;
PyObject *const_str_plain_target;
PyObject *const_str_plain_thread;
PyObject *const_str_plain_unichr;
PyObject *const_str_plain_update;
PyObject *const_str_plain_values;
PyObject *const_str_plain_winreg;
PyObject *const_str_plain_xrange;
PyObject *const_tuple_none_tuple;
PyObject *const_tuple_true_tuple;
PyObject *const_str_angle_genexpr;
PyObject *const_str_plain_BytesIO;
PyObject *const_str_plain_OpenKey;
PyObject *const_str_plain_Surface;
PyObject *const_str_plain_SysFont;
PyObject *const_str_plain___all__;
PyObject *const_str_plain___cmp__;
PyObject *const_str_plain___doc__;
PyObject *const_str_plain___len__;
PyObject *const_str_plain__winreg;
PyObject *const_str_plain_array2d;
PyObject *const_str_plain_array3d;
PyObject *const_str_plain_compile;
PyObject *const_str_plain_copyreg;
PyObject *const_str_plain_dirname;
PyObject *const_str_plain_display;
PyObject *const_str_plain_environ;
PyObject *const_str_plain_globals;
PyObject *const_str_plain_inspect;
PyObject *const_str_plain_modules;
PyObject *const_str_plain_oblique;
PyObject *const_str_plain_replace;
PyObject *const_str_plain_samples;
PyObject *const_str_plain_surface;
PyObject *const_str_plain_unicode;
PyObject *const_str_plain_xrange_;
PyObject *const_tuple_int_0_tuple;
PyObject *const_str_angle_listcomp;
PyObject *const_str_plain_StringIO;
PyObject *const_str_plain___call__;
PyObject *const_str_plain___dict__;
PyObject *const_str_plain___exit__;
PyObject *const_str_plain___file__;
PyObject *const_str_plain___init__;
PyObject *const_str_plain___iter__;
PyObject *const_str_plain___main__;
PyObject *const_str_plain___name__;
PyObject *const_str_plain___path__;
PyObject *const_str_plain___spec__;
PyObject *const_str_plain_as_bytes;
PyObject *const_str_plain_basename;
PyObject *const_str_plain_callable;
PyObject *const_str_plain_copy_reg;
PyObject *const_str_plain_exc_info;
PyObject *const_str_plain_fontpath;
PyObject *const_str_plain_fromlist;
PyObject *const_str_plain_get_rect;
PyObject *const_str_plain_get_size;
PyObject *const_str_plain_geterror;
PyObject *const_str_plain_normpath;
PyObject *const_str_plain_operator;
PyObject *const_str_plain_pixels2d;
PyObject *const_str_plain_pixels3d;
PyObject *const_str_plain_platform;
PyObject *const_str_plain_property;
PyObject *const_str_plain_set_bold;
PyObject *const_str_plain_splitext;
PyObject *const_str_plain_unicode_;
PyObject *const_str_plain___class__;
PyObject *const_str_plain___debug__;
PyObject *const_str_plain___enter__;
PyObject *const_str_plain_arraytype;
PyObject *const_str_plain_bytearray;
PyObject *const_str_plain_cStringIO;
PyObject *const_str_plain_get_fonts;
PyObject *const_str_plain_itertools;
PyObject *const_str_plain_map_array;
PyObject *const_str_plain_metaclass;
PyObject *const_str_plain_raw_input;
PyObject *const_str_plain_threading;
PyObject *const_str_plain_transform;
PyObject *const_str_plain___author__;
PyObject *const_str_plain___cached__;
PyObject *const_str_plain___import__;
PyObject *const_str_plain___loader__;
PyObject *const_str_plain___module__;
PyObject *const_str_plain_as_unicode;
PyObject *const_str_plain_background;
PyObject *const_str_plain_blit_array;
PyObject *const_str_plain_make_sound;
PyObject *const_str_plain_match_font;
PyObject *const_str_plain_pixels_red;
PyObject *const_str_plain_set_italic;
PyObject *const_str_plain_startswith;
PyObject *const_str_plain_subprocess;
PyObject *const_str_plain___getattr__;
PyObject *const_str_plain___getitem__;
PyObject *const_str_plain___nonzero__;
PyObject *const_str_plain___package__;
PyObject *const_str_plain___prepare__;
PyObject *const_str_plain___version__;
PyObject *const_str_plain_array_alpha;
PyObject *const_str_plain_classmethod;
PyObject *const_str_plain_constructor;
PyObject *const_str_plain_getResource;
PyObject *const_str_plain_get_BytesIO;
PyObject *const_str_plain_pixels_blue;
PyObject *const_tuple_int_pos_1_tuple;
PyObject *const_tuple_none_none_tuple;
PyObject *const_tuple_str_chr_0_tuple;
PyObject *const_str_plain_QueryValueEx;
PyObject *const_str_plain___builtins__;
PyObject *const_str_plain___internal__;
PyObject *const_str_plain___qualname__;
PyObject *const_str_plain_make_surface;
PyObject *const_str_plain_pixels_alpha;
PyObject *const_str_plain_pixels_green;
PyObject *const_str_plain_staticmethod;
PyObject *const_str_plain_version_info;
PyObject *const_str_plain___metaclass__;
PyObject *const_str_plain_get_arraytype;
PyObject *const_str_plain_use_arraytype;
PyObject *const_tuple_int_0_int_0_tuple;
PyObject *const_tuple_str_newline_tuple;
PyObject *const_tuple_str_plain_x_tuple;
PyObject *const_tuple_type_object_tuple;
PyObject *const_str_plain_array_colorkey;
PyObject *const_str_plain_get_arraytypes;
PyObject *const_str_plain_unicode_escape;
PyObject *const_slice_none_int_pos_2_none;
PyObject *const_tuple_str_plain_obj_tuple;
PyObject *const_slice_int_0_int_pos_2_none;
PyObject *const_str_plain_PY_MAJOR_VERSION;
PyObject *const_str_plain_array_to_surface;
PyObject *const_str_plain_encode_file_path;
PyObject *const_tuple_str_plain_Rect_tuple;
PyObject *const_tuple_str_plain_java_tuple;
PyObject *const_tuple_str_plain_name_tuple;
PyObject *const_tuple_str_plain_self_tuple;
PyObject *const_str_plain_getwindowsversion;
PyObject *const_tuple_str_plain_array_tuple;
PyObject *const_tuple_str_plain_numpy_tuple;
PyObject *const_tuple_str_plain_sound_tuple;
PyObject *const_str_plain_HKEY_LOCAL_MACHINE;
PyObject *const_tuple_str_plain_surface_tuple;
PyObject *const_tuple_int_pos_3_int_pos_3_tuple;
PyObject *const_tuple_str_plain___class___tuple;
PyObject *const_tuple_str_plain_arraytype_tuple;
PyObject *const_dict_a7ab110deec347786bcfa718065f5388;
PyObject *const_tuple_str_plain_self_str_plain_args_tuple;
PyObject *const_tuple_str_plain_self_str_plain_value_tuple;
PyObject *const_str_digest_0652bb03f90c2cca6cd14fe6735986b2;
PyObject *const_str_digest_09071ce7627c997b2ddfbec9a930c08b;
PyObject *const_str_digest_11bb5f146c38d7c06053353ff65da84a;
PyObject *const_str_digest_1ef86d6d9cfb907791755ff131616348;
PyObject *const_str_digest_25731c733fd74e8333aa29126ce85686;
PyObject *const_str_digest_311cff636bc9fe2337ef6b561e3a7fa9;
PyObject *const_str_digest_390dcb68817636bbd0641245b5f96e70;
PyObject *const_str_digest_397a17452f1c53e6ae5af26f0cec775b;
PyObject *const_str_digest_436e7eb61b35d39994d896416c082efa;
PyObject *const_str_digest_45e4dde2057b0bf276d6a84f4c917d27;
PyObject *const_str_digest_60ac2b0d0530324399922e9b4f074c7a;
PyObject *const_str_digest_62b7e67e29e99420603c12d205222fa5;
PyObject *const_str_digest_672366ed1fcc7aba1730c8c9e9e92aea;
PyObject *const_str_digest_72035249113faa63f8939ea70bf6ef12;
PyObject *const_str_digest_749448536aec7c722f6b23d71bbbb4b1;
PyObject *const_str_digest_7b06e36aa54006877c6dbd4046f3d7da;
PyObject *const_str_digest_86c7bb6b17330427d0fab757eb020984;
PyObject *const_str_digest_886429de8fdd53f8d5c9561510a627a3;
PyObject *const_str_digest_9816e8d1552296af90d250823c964059;
PyObject *const_str_digest_adc474dd61fbd736d69c1bac5d9712e0;
PyObject *const_str_digest_b010b74deac075981c5003854bdfd1a6;
PyObject *const_str_digest_b2e0d613f6b2aca091d775f4312aede2;
PyObject *const_str_digest_b646956a0fd89f2f0ee5168bcdb2f2b8;
PyObject *const_str_digest_b9c4baf879ebd882d40843df3a4dead7;
PyObject *const_str_digest_be0c58c5fcf712145ccaf4e61ea24ef9;
PyObject *const_str_digest_c075052d723d6707083e869a0e3659bb;
PyObject *const_str_digest_d174e39ef12748481d2d13702313aa6c;
PyObject *const_str_digest_df4bac290232ff9f319b12d3d498971c;
PyObject *const_str_digest_e420c3319159a1e6d3a583b2fbaf6bd0;
PyObject *const_str_digest_ec33b54dbd13f5c2292ba451b0640cb1;
PyObject *const_str_digest_f8b7823bdfb14e2c4cbd75b5ca5fd166;
PyObject *const_tuple_str_plain_surface_str_plain_array_tuple;
PyObject *const_tuple_anon_function_anon_builtin_function_or_method_tuple;
PyObject *const_tuple_str_plain_self_str_plain_args_str_plain_kwargs_tuple;

static void _createGlobalConstants( void )
{
    NUITKA_MAY_BE_UNUSED PyObject *exception_type, *exception_value;
    NUITKA_MAY_BE_UNUSED PyTracebackObject *exception_tb;

#ifdef _MSC_VER
    // Prevent unused warnings in case of simple programs, the attribute
    // NUITKA_MAY_BE_UNUSED doesn't work for MSVC.
    (void *)exception_type; (void *)exception_value; (void *)exception_tb;
#endif

    const_int_0 = PyLong_FromUnsignedLong( 0ul );
    const_str_dot = UNSTREAM_STRING( &constant_bin[ 15 ], 1, 0 );
    const_int_neg_1 = PyLong_FromLong( -1l );
    const_int_pos_1 = PyLong_FromUnsignedLong( 1ul );
    const_int_pos_2 = PyLong_FromUnsignedLong( 2ul );
    const_int_pos_3 = PyLong_FromUnsignedLong( 3ul );
    const_int_pos_4 = PyLong_FromUnsignedLong( 4ul );
    const_int_pos_5 = PyLong_FromUnsignedLong( 5ul );
    const_int_pos_8 = PyLong_FromUnsignedLong( 8ul );
    const_str_chr_0 = UNSTREAM_STRING( &constant_bin[ 25361 ], 1, 0 );
    const_str_empty = UNSTREAM_STRING( &constant_bin[ 0 ], 0, 0 );
    const_str_space = UNSTREAM_STRING( &constant_bin[ 30 ], 1, 0 );
    const_dict_empty = _PyDict_NewPresized( 0 );
    assert( PyDict_Size( const_dict_empty ) == 0 );
    const_int_pos_10 = PyLong_FromUnsignedLong( 10ul );
    const_int_pos_16 = PyLong_FromUnsignedLong( 16ul );
    const_int_pos_20 = PyLong_FromUnsignedLong( 20ul );
    const_int_pos_32 = PyLong_FromUnsignedLong( 32ul );
    const_int_pos_64 = PyLong_FromUnsignedLong( 64ul );
    const_str_chr_44 = UNSTREAM_STRING( &constant_bin[ 191 ], 1, 0 );
    const_bytes_empty = UNSTREAM_BYTES( &constant_bin[ 0 ], 0 );
    const_int_pos_255 = PyLong_FromUnsignedLong( 255ul );
    const_str_newline = UNSTREAM_STRING( &constant_bin[ 1083 ], 1, 0 );
    const_str_plain_X = UNSTREAM_STRING( &constant_bin[ 998 ], 1, 1 );
    const_str_plain__ = UNSTREAM_STRING( &constant_bin[ 16 ], 1, 1 );
    const_str_plain_b = UNSTREAM_STRING( &constant_bin[ 6 ], 1, 1 );
    const_str_plain_c = UNSTREAM_STRING( &constant_bin[ 56 ], 1, 1 );
    const_str_plain_f = UNSTREAM_STRING( &constant_bin[ 157 ], 1, 1 );
    const_str_plain_h = UNSTREAM_STRING( &constant_bin[ 10 ], 1, 1 );
    const_str_plain_i = UNSTREAM_STRING( &constant_bin[ 18 ], 1, 1 );
    const_str_plain_o = UNSTREAM_STRING( &constant_bin[ 2 ], 1, 1 );
    const_str_plain_r = UNSTREAM_STRING( &constant_bin[ 11 ], 1, 1 );
    const_str_plain_s = UNSTREAM_STRING( &constant_bin[ 24 ], 1, 1 );
    const_str_plain_u = UNSTREAM_STRING( &constant_bin[ 50 ], 1, 1 );
    const_str_plain_w = UNSTREAM_STRING( &constant_bin[ 103 ], 1, 1 );
    const_str_plain_x = UNSTREAM_STRING( &constant_bin[ 480 ], 1, 1 );
    const_str_plain_y = UNSTREAM_STRING( &constant_bin[ 91 ], 1, 1 );
    const_tuple_empty = PyTuple_New( 0 );
    const_str_plain_io = UNSTREAM_STRING( &constant_bin[ 403 ], 2, 1 );
    const_str_plain_nt = UNSTREAM_STRING( &constant_bin[ 398 ], 2, 1 );
    const_str_plain_os = UNSTREAM_STRING( &constant_bin[ 795 ], 2, 1 );
    const_str_plain_rb = UNSTREAM_STRING( &constant_bin[ 6105 ], 2, 1 );
    const_str_plain_PY3 = UNSTREAM_STRING( &constant_bin[ 101678 ], 3, 1 );
    const_str_plain_buf = UNSTREAM_STRING( &constant_bin[ 6106 ], 3, 1 );
    const_str_plain_chr = UNSTREAM_STRING( &constant_bin[ 80 ], 3, 1 );
    const_str_plain_doc = UNSTREAM_STRING( &constant_bin[ 2311 ], 3, 1 );
    const_str_plain_end = UNSTREAM_STRING( &constant_bin[ 205 ], 3, 1 );
    const_str_plain_get = UNSTREAM_STRING( &constant_bin[ 6203 ], 3, 1 );
    const_str_plain_int = UNSTREAM_STRING( &constant_bin[ 721 ], 3, 1 );
    const_str_plain_key = UNSTREAM_STRING( &constant_bin[ 13899 ], 3, 1 );
    const_str_plain_len = UNSTREAM_STRING( &constant_bin[ 15160 ], 3, 1 );
    const_str_plain_map = UNSTREAM_STRING( &constant_bin[ 19971 ], 3, 1 );
    const_str_plain_mod = UNSTREAM_STRING( &constant_bin[ 786 ], 3, 1 );
    const_str_plain_obj = UNSTREAM_STRING( &constant_bin[ 15401 ], 3, 1 );
    const_str_plain_pop = UNSTREAM_STRING( &constant_bin[ 105846 ], 3, 1 );
    const_str_plain_sep = UNSTREAM_STRING( &constant_bin[ 13764 ], 3, 1 );
    const_str_plain_str = UNSTREAM_STRING( &constant_bin[ 1280 ], 3, 1 );
    const_str_plain_sum = UNSTREAM_STRING( &constant_bin[ 702 ], 3, 1 );
    const_str_plain_sys = UNSTREAM_STRING( &constant_bin[ 1161 ], 3, 1 );
    const_str_plain_val = UNSTREAM_STRING( &constant_bin[ 2741 ], 3, 1 );
    const_str_plain_ver = UNSTREAM_STRING( &constant_bin[ 489 ], 3, 1 );
    const_str_plain_Font = UNSTREAM_STRING( &constant_bin[ 52506 ], 4, 1 );
    const_str_plain_None = UNSTREAM_STRING( &constant_bin[ 1146 ], 4, 1 );
    const_str_plain_Rect = UNSTREAM_STRING( &constant_bin[ 63077 ], 4, 1 );
    const_str_plain_args = UNSTREAM_STRING( &constant_bin[ 51486 ], 4, 1 );
    const_str_plain_argv = UNSTREAM_STRING( &constant_bin[ 105849 ], 4, 1 );
    const_str_plain_blit = UNSTREAM_STRING( &constant_bin[ 778 ], 4, 1 );
    const_str_plain_bold = UNSTREAM_STRING( &constant_bin[ 520 ], 4, 1 );
    const_str_plain_copy = UNSTREAM_STRING( &constant_bin[ 15472 ], 4, 1 );
    const_str_plain_data = UNSTREAM_STRING( &constant_bin[ 924 ], 4, 1 );
    const_str_plain_dict = UNSTREAM_STRING( &constant_bin[ 25276 ], 4, 1 );
    const_str_plain_draw = UNSTREAM_STRING( &constant_bin[ 14014 ], 4, 1 );
    const_str_plain_file = UNSTREAM_STRING( &constant_bin[ 2607 ], 4, 1 );
    const_str_plain_font = UNSTREAM_STRING( &constant_bin[ 15438 ], 4, 1 );
    const_str_plain_imap = UNSTREAM_STRING( &constant_bin[ 46724 ], 4, 1 );
    const_str_plain_info = UNSTREAM_STRING( &constant_bin[ 11972 ], 4, 1 );
    const_str_plain_init = UNSTREAM_STRING( &constant_bin[ 18 ], 4, 1 );
    const_str_plain_iter = UNSTREAM_STRING( &constant_bin[ 46742 ], 4, 1 );
    const_str_plain_java = UNSTREAM_STRING( &constant_bin[ 6312 ], 4, 1 );
    const_str_plain_join = UNSTREAM_STRING( &constant_bin[ 56811 ], 4, 1 );
    const_str_plain_keys = UNSTREAM_STRING( &constant_bin[ 98620 ], 4, 1 );
    const_str_plain_left = UNSTREAM_STRING( &constant_bin[ 473 ], 4, 1 );
    const_str_plain_line = UNSTREAM_STRING( &constant_bin[ 36381 ], 4, 1 );
    const_str_plain_long = UNSTREAM_STRING( &constant_bin[ 22611 ], 4, 1 );
    const_str_plain_mask = UNSTREAM_STRING( &constant_bin[ 50893 ], 4, 1 );
    const_str_plain_name = UNSTREAM_STRING( &constant_bin[ 1010 ], 4, 1 );
    const_str_plain_next = UNSTREAM_STRING( &constant_bin[ 46719 ], 4, 1 );
    const_str_plain_open = UNSTREAM_STRING( &constant_bin[ 92393 ], 4, 1 );
    const_str_plain_path = UNSTREAM_STRING( &constant_bin[ 1026 ], 4, 1 );
    const_str_plain_quit = UNSTREAM_STRING( &constant_bin[ 105853 ], 4, 1 );
    const_str_plain_read = UNSTREAM_STRING( &constant_bin[ 11 ], 4, 1 );
    const_str_plain_repr = UNSTREAM_STRING( &constant_bin[ 21665 ], 4, 1 );
    const_str_plain_self = UNSTREAM_STRING( &constant_bin[ 64495 ], 4, 1 );
    const_str_plain_send = UNSTREAM_STRING( &constant_bin[ 105857 ], 4, 1 );
    const_str_plain_site = UNSTREAM_STRING( &constant_bin[ 9560 ], 4, 1 );
    const_str_plain_size = UNSTREAM_STRING( &constant_bin[ 6373 ], 4, 1 );
    const_str_plain_stop = UNSTREAM_STRING( &constant_bin[ 334 ], 4, 1 );
    const_str_plain_time = UNSTREAM_STRING( &constant_bin[ 14762 ], 4, 1 );
    const_str_plain_type = UNSTREAM_STRING( &constant_bin[ 6077 ], 4, 1 );
    const_str_plain_wait = UNSTREAM_STRING( &constant_bin[ 275 ], 4, 1 );
    const_str_plain_Color = UNSTREAM_STRING( &constant_bin[ 54027 ], 5, 1 );
    const_str_plain_False = UNSTREAM_STRING( &constant_bin[ 1424 ], 5, 1 );
    const_str_plain_Queue = UNSTREAM_STRING( &constant_bin[ 95449 ], 5, 1 );
    const_str_plain_array = UNSTREAM_STRING( &constant_bin[ 14617 ], 5, 1 );
    const_str_plain_ascii = UNSTREAM_STRING( &constant_bin[ 94821 ], 5, 1 );
    const_str_plain_bytes = UNSTREAM_STRING( &constant_bin[ 18989 ], 5, 1 );
    const_str_plain_close = UNSTREAM_STRING( &constant_bin[ 77782 ], 5, 1 );
    const_str_plain_color = UNSTREAM_STRING( &constant_bin[ 14156 ], 5, 1 );
    const_str_plain_empty = UNSTREAM_STRING( &constant_bin[ 18911 ], 5, 1 );
    const_str_plain_event = UNSTREAM_STRING( &constant_bin[ 741 ], 5, 1 );
    const_str_plain_image = UNSTREAM_STRING( &constant_bin[ 14249 ], 5, 1 );
    const_str_plain_input = UNSTREAM_STRING( &constant_bin[ 46676 ], 5, 1 );
    const_str_plain_items = UNSTREAM_STRING( &constant_bin[ 99257 ], 5, 1 );
    const_str_plain_level = UNSTREAM_STRING( &constant_bin[ 105861 ], 5, 1 );
    const_str_plain_lower = UNSTREAM_STRING( &constant_bin[ 28956 ], 5, 1 );
    const_str_plain_mixer = UNSTREAM_STRING( &constant_bin[ 14962 ], 5, 1 );
    const_str_plain_mouse = UNSTREAM_STRING( &constant_bin[ 14635 ], 5, 1 );
    const_str_plain_numpy = UNSTREAM_STRING( &constant_bin[ 15629 ], 5, 1 );
    const_str_plain_print = UNSTREAM_STRING( &constant_bin[ 100252 ], 5, 1 );
    const_str_plain_queue = UNSTREAM_STRING( &constant_bin[ 95461 ], 5, 1 );
    const_str_plain_range = UNSTREAM_STRING( &constant_bin[ 26476 ], 5, 1 );
    const_str_plain_right = UNSTREAM_STRING( &constant_bin[ 229 ], 5, 1 );
    const_str_plain_shell = UNSTREAM_STRING( &constant_bin[ 6059 ], 5, 1 );
    const_str_plain_sound = UNSTREAM_STRING( &constant_bin[ 15981 ], 5, 1 );
    const_str_plain_split = UNSTREAM_STRING( &constant_bin[ 99155 ], 5, 1 );
    const_str_plain_start = UNSTREAM_STRING( &constant_bin[ 64629 ], 5, 1 );
    const_str_plain_throw = UNSTREAM_STRING( &constant_bin[ 534 ], 5, 1 );
    const_str_plain_tuple = UNSTREAM_STRING( &constant_bin[ 51291 ], 5, 1 );
    const_str_plain_types = UNSTREAM_STRING( &constant_bin[ 6077 ], 5, 1 );
    const_str_plain_value = UNSTREAM_STRING( &constant_bin[ 2741 ], 5, 1 );
    const_str_plain_width = UNSTREAM_STRING( &constant_bin[ 51042 ], 5, 1 );
    const_str_plain_win32 = UNSTREAM_STRING( &constant_bin[ 4542 ], 5, 1 );
    const_str_angle_lambda = UNSTREAM_STRING( &constant_bin[ 71295 ], 8, 0 );
    const_str_plain_Thread = UNSTREAM_STRING( &constant_bin[ 9 ], 6, 1 );
    const_str_plain_append = UNSTREAM_STRING( &constant_bin[ 1502 ], 6, 1 );
    const_str_plain_bytes_ = UNSTREAM_STRING( &constant_bin[ 104059 ], 6, 1 );
    const_str_plain_darwin = UNSTREAM_STRING( &constant_bin[ 93756 ], 6, 1 );
    const_str_plain_decode = UNSTREAM_STRING( &constant_bin[ 105866 ], 6, 1 );
    const_str_plain_encode = UNSTREAM_STRING( &constant_bin[ 13846 ], 6, 1 );
    const_str_plain_exists = UNSTREAM_STRING( &constant_bin[ 56370 ], 6, 1 );
    const_str_plain_filter = UNSTREAM_STRING( &constant_bin[ 102709 ], 6, 1 );
    const_str_plain_format = UNSTREAM_STRING( &constant_bin[ 15904 ], 6, 1 );
    const_str_plain_getcwd = UNSTREAM_STRING( &constant_bin[ 101554 ], 6, 1 );
    const_str_plain_height = UNSTREAM_STRING( &constant_bin[ 52608 ], 6, 1 );
    const_str_plain_italic = UNSTREAM_STRING( &constant_bin[ 53079 ], 6, 1 );
    const_str_plain_kwargs = UNSTREAM_STRING( &constant_bin[ 59624 ], 6, 1 );
    const_str_plain_locals = UNSTREAM_STRING( &constant_bin[ 52312 ], 6, 1 );
    const_str_plain_object = UNSTREAM_STRING( &constant_bin[ 15401 ], 6, 1 );
    const_str_plain_pickle = UNSTREAM_STRING( &constant_bin[ 105872 ], 6, 1 );
    const_str_plain_pygame = UNSTREAM_STRING( &constant_bin[ 13826 ], 6, 1 );
    const_str_plain_remove = UNSTREAM_STRING( &constant_bin[ 13945 ], 6, 1 );
    const_str_plain_render = UNSTREAM_STRING( &constant_bin[ 52424 ], 6, 1 );
    const_str_plain_result = UNSTREAM_STRING( &constant_bin[ 95376 ], 6, 1 );
    const_str_plain_rstrip = UNSTREAM_STRING( &constant_bin[ 105878 ], 6, 1 );
    const_str_plain_sprite = UNSTREAM_STRING( &constant_bin[ 59593 ], 6, 1 );
    const_str_plain_stdout = UNSTREAM_STRING( &constant_bin[ 105884 ], 6, 1 );
    const_str_plain_strict = UNSTREAM_STRING( &constant_bin[ 105890 ], 6, 1 );
    const_str_plain_target = UNSTREAM_STRING( &constant_bin[ 105896 ], 6, 1 );
    const_str_plain_thread = UNSTREAM_STRING( &constant_bin[ 387 ], 6, 1 );
    const_str_plain_unichr = UNSTREAM_STRING( &constant_bin[ 46712 ], 6, 1 );
    const_str_plain_update = UNSTREAM_STRING( &constant_bin[ 59358 ], 6, 1 );
    const_str_plain_values = UNSTREAM_STRING( &constant_bin[ 16774 ], 6, 1 );
    const_str_plain_winreg = UNSTREAM_STRING( &constant_bin[ 105902 ], 6, 1 );
    const_str_plain_xrange = UNSTREAM_STRING( &constant_bin[ 105908 ], 6, 1 );
    const_tuple_none_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_none_tuple, 0, Py_None ); Py_INCREF( Py_None );
    const_tuple_true_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_true_tuple, 0, Py_True ); Py_INCREF( Py_True );
    const_str_angle_genexpr = UNSTREAM_STRING( &constant_bin[ 93637 ], 9, 0 );
    const_str_plain_BytesIO = UNSTREAM_STRING( &constant_bin[ 105914 ], 7, 1 );
    const_str_plain_OpenKey = UNSTREAM_STRING( &constant_bin[ 105921 ], 7, 1 );
    const_str_plain_Surface = UNSTREAM_STRING( &constant_bin[ 17192 ], 7, 1 );
    const_str_plain_SysFont = UNSTREAM_STRING( &constant_bin[ 53047 ], 7, 1 );
    const_str_plain___all__ = UNSTREAM_STRING( &constant_bin[ 105928 ], 7, 1 );
    const_str_plain___cmp__ = UNSTREAM_STRING( &constant_bin[ 105935 ], 7, 1 );
    const_str_plain___doc__ = UNSTREAM_STRING( &constant_bin[ 105942 ], 7, 1 );
    const_str_plain___len__ = UNSTREAM_STRING( &constant_bin[ 75804 ], 7, 1 );
    const_str_plain__winreg = UNSTREAM_STRING( &constant_bin[ 105949 ], 7, 1 );
    const_str_plain_array2d = UNSTREAM_STRING( &constant_bin[ 22413 ], 7, 1 );
    const_str_plain_array3d = UNSTREAM_STRING( &constant_bin[ 22396 ], 7, 1 );
    const_str_plain_compile = UNSTREAM_STRING( &constant_bin[ 48214 ], 7, 1 );
    const_str_plain_copyreg = UNSTREAM_STRING( &constant_bin[ 105956 ], 7, 1 );
    const_str_plain_dirname = UNSTREAM_STRING( &constant_bin[ 56749 ], 7, 1 );
    const_str_plain_display = UNSTREAM_STRING( &constant_bin[ 15556 ], 7, 1 );
    const_str_plain_environ = UNSTREAM_STRING( &constant_bin[ 105963 ], 7, 1 );
    const_str_plain_globals = UNSTREAM_STRING( &constant_bin[ 98466 ], 7, 1 );
    const_str_plain_inspect = UNSTREAM_STRING( &constant_bin[ 105970 ], 7, 1 );
    const_str_plain_modules = UNSTREAM_STRING( &constant_bin[ 15091 ], 7, 1 );
    const_str_plain_oblique = UNSTREAM_STRING( &constant_bin[ 105977 ], 7, 1 );
    const_str_plain_replace = UNSTREAM_STRING( &constant_bin[ 105984 ], 7, 1 );
    const_str_plain_samples = UNSTREAM_STRING( &constant_bin[ 15667 ], 7, 1 );
    const_str_plain_surface = UNSTREAM_STRING( &constant_bin[ 13885 ], 7, 1 );
    const_str_plain_unicode = UNSTREAM_STRING( &constant_bin[ 11904 ], 7, 1 );
    const_str_plain_xrange_ = UNSTREAM_STRING( &constant_bin[ 105991 ], 7, 1 );
    const_tuple_int_0_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_0_tuple, 0, const_int_0 ); Py_INCREF( const_int_0 );
    const_str_angle_listcomp = UNSTREAM_STRING( &constant_bin[ 105998 ], 10, 0 );
    const_str_plain_StringIO = UNSTREAM_STRING( &constant_bin[ 46816 ], 8, 1 );
    const_str_plain___call__ = UNSTREAM_STRING( &constant_bin[ 62337 ], 8, 1 );
    const_str_plain___dict__ = UNSTREAM_STRING( &constant_bin[ 106008 ], 8, 1 );
    const_str_plain___exit__ = UNSTREAM_STRING( &constant_bin[ 106016 ], 8, 1 );
    const_str_plain___file__ = UNSTREAM_STRING( &constant_bin[ 56438 ], 8, 1 );
    const_str_plain___init__ = UNSTREAM_STRING( &constant_bin[ 16 ], 8, 1 );
    const_str_plain___iter__ = UNSTREAM_STRING( &constant_bin[ 83354 ], 8, 1 );
    const_str_plain___main__ = UNSTREAM_STRING( &constant_bin[ 106024 ], 8, 1 );
    const_str_plain___name__ = UNSTREAM_STRING( &constant_bin[ 56712 ], 8, 1 );
    const_str_plain___path__ = UNSTREAM_STRING( &constant_bin[ 106032 ], 8, 1 );
    const_str_plain___spec__ = UNSTREAM_STRING( &constant_bin[ 106040 ], 8, 1 );
    const_str_plain_as_bytes = UNSTREAM_STRING( &constant_bin[ 106048 ], 8, 1 );
    const_str_plain_basename = UNSTREAM_STRING( &constant_bin[ 106056 ], 8, 1 );
    const_str_plain_callable = UNSTREAM_STRING( &constant_bin[ 61571 ], 8, 1 );
    const_str_plain_copy_reg = UNSTREAM_STRING( &constant_bin[ 106064 ], 8, 1 );
    const_str_plain_exc_info = UNSTREAM_STRING( &constant_bin[ 106072 ], 8, 1 );
    const_str_plain_fontpath = UNSTREAM_STRING( &constant_bin[ 53905 ], 8, 1 );
    const_str_plain_fromlist = UNSTREAM_STRING( &constant_bin[ 106080 ], 8, 1 );
    const_str_plain_get_rect = UNSTREAM_STRING( &constant_bin[ 106088 ], 8, 1 );
    const_str_plain_get_size = UNSTREAM_STRING( &constant_bin[ 55030 ], 8, 1 );
    const_str_plain_geterror = UNSTREAM_STRING( &constant_bin[ 106096 ], 8, 1 );
    const_str_plain_normpath = UNSTREAM_STRING( &constant_bin[ 56865 ], 8, 1 );
    const_str_plain_operator = UNSTREAM_STRING( &constant_bin[ 82340 ], 8, 1 );
    const_str_plain_pixels2d = UNSTREAM_STRING( &constant_bin[ 20040 ], 8, 1 );
    const_str_plain_pixels3d = UNSTREAM_STRING( &constant_bin[ 24330 ], 8, 1 );
    const_str_plain_platform = UNSTREAM_STRING( &constant_bin[ 11774 ], 8, 1 );
    const_str_plain_property = UNSTREAM_STRING( &constant_bin[ 106104 ], 8, 1 );
    const_str_plain_set_bold = UNSTREAM_STRING( &constant_bin[ 54464 ], 8, 1 );
    const_str_plain_splitext = UNSTREAM_STRING( &constant_bin[ 106112 ], 8, 1 );
    const_str_plain_unicode_ = UNSTREAM_STRING( &constant_bin[ 11904 ], 8, 1 );
    const_str_plain___class__ = UNSTREAM_STRING( &constant_bin[ 106120 ], 9, 1 );
    const_str_plain___debug__ = UNSTREAM_STRING( &constant_bin[ 106129 ], 9, 1 );
    const_str_plain___enter__ = UNSTREAM_STRING( &constant_bin[ 106138 ], 9, 1 );
    const_str_plain_arraytype = UNSTREAM_STRING( &constant_bin[ 57088 ], 9, 1 );
    const_str_plain_bytearray = UNSTREAM_STRING( &constant_bin[ 106147 ], 9, 1 );
    const_str_plain_cStringIO = UNSTREAM_STRING( &constant_bin[ 106156 ], 9, 1 );
    const_str_plain_get_fonts = UNSTREAM_STRING( &constant_bin[ 92838 ], 9, 1 );
    const_str_plain_itertools = UNSTREAM_STRING( &constant_bin[ 106165 ], 9, 1 );
    const_str_plain_map_array = UNSTREAM_STRING( &constant_bin[ 19971 ], 9, 1 );
    const_str_plain_metaclass = UNSTREAM_STRING( &constant_bin[ 99835 ], 9, 1 );
    const_str_plain_raw_input = UNSTREAM_STRING( &constant_bin[ 46672 ], 9, 1 );
    const_str_plain_threading = UNSTREAM_STRING( &constant_bin[ 96918 ], 9, 1 );
    const_str_plain_transform = UNSTREAM_STRING( &constant_bin[ 106174 ], 9, 1 );
    const_str_plain___author__ = UNSTREAM_STRING( &constant_bin[ 106183 ], 10, 1 );
    const_str_plain___cached__ = UNSTREAM_STRING( &constant_bin[ 106193 ], 10, 1 );
    const_str_plain___import__ = UNSTREAM_STRING( &constant_bin[ 106203 ], 10, 1 );
    const_str_plain___loader__ = UNSTREAM_STRING( &constant_bin[ 56900 ], 10, 1 );
    const_str_plain___module__ = UNSTREAM_STRING( &constant_bin[ 106213 ], 10, 1 );
    const_str_plain_as_unicode = UNSTREAM_STRING( &constant_bin[ 106223 ], 10, 1 );
    const_str_plain_background = UNSTREAM_STRING( &constant_bin[ 54394 ], 10, 1 );
    const_str_plain_blit_array = UNSTREAM_STRING( &constant_bin[ 106233 ], 10, 1 );
    const_str_plain_make_sound = UNSTREAM_STRING( &constant_bin[ 15976 ], 10, 1 );
    const_str_plain_match_font = UNSTREAM_STRING( &constant_bin[ 92428 ], 10, 1 );
    const_str_plain_pixels_red = UNSTREAM_STRING( &constant_bin[ 19060 ], 10, 1 );
    const_str_plain_set_italic = UNSTREAM_STRING( &constant_bin[ 54536 ], 10, 1 );
    const_str_plain_startswith = UNSTREAM_STRING( &constant_bin[ 106243 ], 10, 1 );
    const_str_plain_subprocess = UNSTREAM_STRING( &constant_bin[ 106253 ], 10, 1 );
    const_str_plain___getattr__ = UNSTREAM_STRING( &constant_bin[ 14505 ], 11, 1 );
    const_str_plain___getitem__ = UNSTREAM_STRING( &constant_bin[ 106263 ], 11, 1 );
    const_str_plain___nonzero__ = UNSTREAM_STRING( &constant_bin[ 13965 ], 11, 1 );
    const_str_plain___package__ = UNSTREAM_STRING( &constant_bin[ 106274 ], 11, 1 );
    const_str_plain___prepare__ = UNSTREAM_STRING( &constant_bin[ 99864 ], 11, 1 );
    const_str_plain___version__ = UNSTREAM_STRING( &constant_bin[ 106285 ], 11, 1 );
    const_str_plain_array_alpha = UNSTREAM_STRING( &constant_bin[ 19508 ], 11, 1 );
    const_str_plain_classmethod = UNSTREAM_STRING( &constant_bin[ 106296 ], 11, 1 );
    const_str_plain_constructor = UNSTREAM_STRING( &constant_bin[ 14382 ], 11, 1 );
    const_str_plain_getResource = UNSTREAM_STRING( &constant_bin[ 55866 ], 11, 1 );
    const_str_plain_get_BytesIO = UNSTREAM_STRING( &constant_bin[ 106307 ], 11, 1 );
    const_str_plain_pixels_blue = UNSTREAM_STRING( &constant_bin[ 18057 ], 11, 1 );
    const_tuple_int_pos_1_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_1_tuple, 0, const_int_pos_1 ); Py_INCREF( const_int_pos_1 );
    const_tuple_none_none_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_none_none_tuple, 0, Py_None ); Py_INCREF( Py_None );
    PyTuple_SET_ITEM( const_tuple_none_none_tuple, 1, Py_None ); Py_INCREF( Py_None );
    const_tuple_str_chr_0_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_chr_0_tuple, 0, const_str_chr_0 ); Py_INCREF( const_str_chr_0 );
    const_str_plain_QueryValueEx = UNSTREAM_STRING( &constant_bin[ 106318 ], 12, 1 );
    const_str_plain___builtins__ = UNSTREAM_STRING( &constant_bin[ 106330 ], 12, 1 );
    const_str_plain___internal__ = UNSTREAM_STRING( &constant_bin[ 106342 ], 12, 1 );
    const_str_plain___qualname__ = UNSTREAM_STRING( &constant_bin[ 106354 ], 12, 1 );
    const_str_plain_make_surface = UNSTREAM_STRING( &constant_bin[ 17149 ], 12, 1 );
    const_str_plain_pixels_alpha = UNSTREAM_STRING( &constant_bin[ 17179 ], 12, 1 );
    const_str_plain_pixels_green = UNSTREAM_STRING( &constant_bin[ 23839 ], 12, 1 );
    const_str_plain_staticmethod = UNSTREAM_STRING( &constant_bin[ 106366 ], 12, 1 );
    const_str_plain_version_info = UNSTREAM_STRING( &constant_bin[ 11964 ], 12, 1 );
    const_str_plain___metaclass__ = UNSTREAM_STRING( &constant_bin[ 106378 ], 13, 1 );
    const_str_plain_get_arraytype = UNSTREAM_STRING( &constant_bin[ 57501 ], 13, 1 );
    const_str_plain_use_arraytype = UNSTREAM_STRING( &constant_bin[ 57084 ], 13, 1 );
    const_tuple_int_0_int_0_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_0_tuple, 0, const_int_0 ); Py_INCREF( const_int_0 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_0_tuple, 1, const_int_0 ); Py_INCREF( const_int_0 );
    const_tuple_str_newline_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_newline_tuple, 0, const_str_newline ); Py_INCREF( const_str_newline );
    const_tuple_str_plain_x_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_x_tuple, 0, const_str_plain_x ); Py_INCREF( const_str_plain_x );
    const_tuple_type_object_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_type_object_tuple, 0, (PyObject *)&PyBaseObject_Type ); Py_INCREF( (PyObject *)&PyBaseObject_Type );
    const_str_plain_array_colorkey = UNSTREAM_STRING( &constant_bin[ 20614 ], 14, 1 );
    const_str_plain_get_arraytypes = UNSTREAM_STRING( &constant_bin[ 58795 ], 14, 1 );
    const_str_plain_unicode_escape = UNSTREAM_STRING( &constant_bin[ 106391 ], 14, 1 );
    const_slice_none_int_pos_2_none = PySlice_New( Py_None, const_int_pos_2, Py_None );
    const_tuple_str_plain_obj_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_obj_tuple, 0, const_str_plain_obj ); Py_INCREF( const_str_plain_obj );
    const_slice_int_0_int_pos_2_none = PySlice_New( const_int_0, const_int_pos_2, Py_None );
    const_str_plain_PY_MAJOR_VERSION = UNSTREAM_STRING( &constant_bin[ 106405 ], 16, 1 );
    const_str_plain_array_to_surface = UNSTREAM_STRING( &constant_bin[ 106421 ], 16, 1 );
    const_str_plain_encode_file_path = UNSTREAM_STRING( &constant_bin[ 52512 ], 16, 1 );
    const_tuple_str_plain_Rect_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_Rect_tuple, 0, const_str_plain_Rect ); Py_INCREF( const_str_plain_Rect );
    const_tuple_str_plain_java_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_java_tuple, 0, const_str_plain_java ); Py_INCREF( const_str_plain_java );
    const_tuple_str_plain_name_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_name_tuple, 0, const_str_plain_name ); Py_INCREF( const_str_plain_name );
    const_tuple_str_plain_self_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    const_str_plain_getwindowsversion = UNSTREAM_STRING( &constant_bin[ 106437 ], 17, 1 );
    const_tuple_str_plain_array_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_array_tuple, 0, const_str_plain_array ); Py_INCREF( const_str_plain_array );
    const_tuple_str_plain_numpy_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_numpy_tuple, 0, const_str_plain_numpy ); Py_INCREF( const_str_plain_numpy );
    const_tuple_str_plain_sound_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_sound_tuple, 0, const_str_plain_sound ); Py_INCREF( const_str_plain_sound );
    const_str_plain_HKEY_LOCAL_MACHINE = UNSTREAM_STRING( &constant_bin[ 106454 ], 18, 1 );
    const_tuple_str_plain_surface_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_surface_tuple, 0, const_str_plain_surface ); Py_INCREF( const_str_plain_surface );
    const_tuple_int_pos_3_int_pos_3_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_int_pos_3_int_pos_3_tuple, 0, const_int_pos_3 ); Py_INCREF( const_int_pos_3 );
    PyTuple_SET_ITEM( const_tuple_int_pos_3_int_pos_3_tuple, 1, const_int_pos_3 ); Py_INCREF( const_int_pos_3 );
    const_tuple_str_plain___class___tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain___class___tuple, 0, const_str_plain___class__ ); Py_INCREF( const_str_plain___class__ );
    const_tuple_str_plain_arraytype_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_arraytype_tuple, 0, const_str_plain_arraytype ); Py_INCREF( const_str_plain_arraytype );
    const_dict_a7ab110deec347786bcfa718065f5388 = _PyDict_NewPresized( 1 );
    PyDict_SetItem( const_dict_a7ab110deec347786bcfa718065f5388, const_str_plain_copy, Py_False );
    assert( PyDict_Size( const_dict_a7ab110deec347786bcfa718065f5388 ) == 1 );
    const_tuple_str_plain_self_str_plain_args_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_args_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_args_tuple, 1, const_str_plain_args ); Py_INCREF( const_str_plain_args );
    const_tuple_str_plain_self_str_plain_value_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_value_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_value_tuple, 1, const_str_plain_value ); Py_INCREF( const_str_plain_value );
    const_str_digest_0652bb03f90c2cca6cd14fe6735986b2 = UNSTREAM_STRING( &constant_bin[ 106472 ], 11, 0 );
    const_str_digest_09071ce7627c997b2ddfbec9a930c08b = UNSTREAM_STRING( &constant_bin[ 92323 ], 14, 0 );
    const_str_digest_11bb5f146c38d7c06053353ff65da84a = UNSTREAM_STRING( &constant_bin[ 92416 ], 11, 0 );
    const_str_digest_1ef86d6d9cfb907791755ff131616348 = UNSTREAM_STRING( &constant_bin[ 59586 ], 13, 0 );
    const_str_digest_25731c733fd74e8333aa29126ce85686 = UNSTREAM_STRING( &constant_bin[ 15946 ], 2, 0 );
    const_str_digest_311cff636bc9fe2337ef6b561e3a7fa9 = UNSTREAM_STRING( &constant_bin[ 46583 ], 13, 0 );
    const_str_digest_390dcb68817636bbd0641245b5f96e70 = UNSTREAM_STRING( &constant_bin[ 106483 ], 18, 0 );
    const_str_digest_397a17452f1c53e6ae5af26f0cec775b = UNSTREAM_STRING( &constant_bin[ 57068 ], 15, 0 );
    const_str_digest_436e7eb61b35d39994d896416c082efa = UNSTREAM_STRING( &constant_bin[ 48023 ], 14, 0 );
    const_str_digest_45e4dde2057b0bf276d6a84f4c917d27 = UNSTREAM_STRING( &constant_bin[ 15816 ], 7, 0 );
    const_str_digest_60ac2b0d0530324399922e9b4f074c7a = UNSTREAM_STRING( &constant_bin[ 56331 ], 14, 0 );
    const_str_digest_62b7e67e29e99420603c12d205222fa5 = UNSTREAM_STRING( &constant_bin[ 106501 ], 7, 0 );
    const_str_digest_672366ed1fcc7aba1730c8c9e9e92aea = UNSTREAM_STRING( &constant_bin[ 15645 ], 21, 0 );
    const_str_digest_72035249113faa63f8939ea70bf6ef12 = UNSTREAM_STRING( &constant_bin[ 106508 ], 16, 0 );
    const_str_digest_749448536aec7c722f6b23d71bbbb4b1 = UNSTREAM_STRING( &constant_bin[ 106524 ], 14, 0 );
    const_str_digest_7b06e36aa54006877c6dbd4046f3d7da = UNSTREAM_STRING( &constant_bin[ 106538 ], 487, 0 );
    const_str_digest_86c7bb6b17330427d0fab757eb020984 = UNSTREAM_STRING( &constant_bin[ 107025 ], 11, 0 );
    const_str_digest_886429de8fdd53f8d5c9561510a627a3 = UNSTREAM_STRING( &constant_bin[ 52895 ], 13, 0 );
    const_str_digest_9816e8d1552296af90d250823c964059 = UNSTREAM_STRING( &constant_bin[ 107036 ], 46, 0 );
    const_str_digest_adc474dd61fbd736d69c1bac5d9712e0 = UNSTREAM_STRING( &constant_bin[ 107082 ], 47, 0 );
    const_str_digest_b010b74deac075981c5003854bdfd1a6 = UNSTREAM_STRING( &constant_bin[ 21160 ], 22, 0 );
    const_str_digest_b2e0d613f6b2aca091d775f4312aede2 = UNSTREAM_STRING( &constant_bin[ 97541 ], 14, 0 );
    const_str_digest_b646956a0fd89f2f0ee5168bcdb2f2b8 = UNSTREAM_STRING( &constant_bin[ 55492 ], 13, 0 );
    const_str_digest_b9c4baf879ebd882d40843df3a4dead7 = UNSTREAM_STRING( &constant_bin[ 2666 ], 2, 1 );
    const_str_digest_be0c58c5fcf712145ccaf4e61ea24ef9 = UNSTREAM_STRING( &constant_bin[ 107129 ], 236, 0 );
    const_str_digest_c075052d723d6707083e869a0e3659bb = UNSTREAM_STRING( &constant_bin[ 107365 ], 5, 0 );
    const_str_digest_d174e39ef12748481d2d13702313aa6c = UNSTREAM_STRING( &constant_bin[ 18040 ], 16, 0 );
    const_str_digest_df4bac290232ff9f319b12d3d498971c = UNSTREAM_STRING( &constant_bin[ 25264 ], 16, 0 );
    const_str_digest_e420c3319159a1e6d3a583b2fbaf6bd0 = UNSTREAM_STRING( &constant_bin[ 107370 ], 16, 0 );
    const_str_digest_ec33b54dbd13f5c2292ba451b0640cb1 = UNSTREAM_STRING( &constant_bin[ 107386 ], 16, 0 );
    const_str_digest_f8b7823bdfb14e2c4cbd75b5ca5fd166 = UNSTREAM_STRING( &constant_bin[ 14955 ], 12, 0 );
    const_tuple_str_plain_surface_str_plain_array_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_surface_str_plain_array_tuple, 0, const_str_plain_surface ); Py_INCREF( const_str_plain_surface );
    PyTuple_SET_ITEM( const_tuple_str_plain_surface_str_plain_array_tuple, 1, const_str_plain_array ); Py_INCREF( const_str_plain_array );
    const_tuple_anon_function_anon_builtin_function_or_method_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_anon_function_anon_builtin_function_or_method_tuple, 0, (PyObject *)&PyFunction_Type ); Py_INCREF( (PyObject *)&PyFunction_Type );
    PyTuple_SET_ITEM( const_tuple_anon_function_anon_builtin_function_or_method_tuple, 1, (PyObject *)&PyCFunction_Type ); Py_INCREF( (PyObject *)&PyCFunction_Type );
    const_tuple_str_plain_self_str_plain_args_str_plain_kwargs_tuple = PyTuple_New( 3 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_args_str_plain_kwargs_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_args_str_plain_kwargs_tuple, 1, const_str_plain_args ); Py_INCREF( const_str_plain_args );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_args_str_plain_kwargs_tuple, 2, const_str_plain_kwargs ); Py_INCREF( const_str_plain_kwargs );

#if _NUITKA_EXE
    /* Set the "sys.executable" path to the original CPython executable. */
    PySys_SetObject(
        (char *)"executable",
        const_str_digest_72035249113faa63f8939ea70bf6ef12
    );
#endif
}

// In debug mode we can check that the constants were not tampered with in any
// given moment. We typically do it at program exit, but we can add extra calls
// for sanity.
#ifndef __NUITKA_NO_ASSERT__
void checkGlobalConstants( void )
{

}
#endif

void createGlobalConstants( void )
{
    if ( _sentinel_value == NULL )
    {
#if PYTHON_VERSION < 300
        _sentinel_value = PyCObject_FromVoidPtr( NULL, NULL );
#else
        // The NULL value is not allowed for a capsule, so use something else.
        _sentinel_value = PyCapsule_New( (void *)27, "sentinel", NULL );
#endif
        assert( _sentinel_value );

        _createGlobalConstants();
    }
}
